name: Publish Docker image

on:
  push:
    branches: ["master"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Install node dependencies
        run: yarn install
      - name: Build node project
        run: yarn run build 
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get lowercase repo name
        id: case_action
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.case_action.outputs.lowercase }}:${{ steps.date.outputs.date }}, ghcr.io/${{ steps.case_action.outputs.lowercase }}:latest
          labels: ${{ steps.meta.outputs.labels }}
